export const StorageKeys = Object.freeze({
  EMPLOYEES: '_EMPLOYEES_KEY',
  DEPARMENTS: '_DEPARMENTS_KEY',
  CURRENT_USER: '_CURRENT_USER_KEY',
  DEGREE: '_DEGREE_KEY',    
  EDUCATION: '_EDUCATION_KEY',   
  EXPERIENCE: '_EXPERIENCE_KEY'     
});